### ISSUE TITLE
Issue with Properties and Interpretations tools not finishing

### ISSUE THREAD

**Issue by ghost** [ncss-tech/SSURGOOnDemandArcPro#3]
SSURGO properties and interpretations tools not loading. Left it running for a day and tried 2 times. I selected a feature in the AOI

I have ArcGIS Pro 3.0.2

**Inputs**: AOI polygon (extracted CLU layer)
                  Selected small field
**Aggregation Method**: Dominant condition
**Soil property*: Hydrologic group

Left defaults for Update attribute table and retain individual tables and message.

**Comment by cferguso** [comment]
I will look into it, but it might take a day or 2.  I am having issues getting arcgis pro installed on a recently reimaged computer.

**Comment by cferguso** [comment]
With a fresh install of Pro 3.0.2 I was able to complete what you were not.  Perhaps you have bad geometry in you AOI?  Did you try running the repair geometry tool or trying a different AOI altogether?


![image](https://user-images.githubusercontent.com/11633071/211903751-9bfe0e1c-586c-4b41-9c98-b7cd07a9ab43.png)

**Comment by ghost** [comment]
Tried with  a different AOI this morning. There may have been an issue with the old one. Both were PLU boundaries from CD. 

It worked this morning with the new AOI.
